version: '3.1'
services:
  API:
    image: 'automatic-irrigation-system'
    container_name: irrigation-system-app
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL

  PostgreSQL:
    image: postgres:13.1-alpine
    container_name: irrigation-system-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=turing-irrigation-system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5